service: cep-find

provider:
  name: aws
  runtime: nodejs10.x


functions:
  cep:
    handler: handler.findOneCep
    events:
      - http: 
          method: GET
          path: cep/{cep}
          
